### ISSUE TITLE
Light: use different color for diff hidden lines section

### ISSUE THREAD

**Issue by svipas** [eamodio/vscode-amethyst-theme#14]
<img width="696" alt="image" src="https://github.com/eamodio/vscode-amethyst-theme/assets/10441177/3772cb25-4f06-4ff8-ae14-9e59b4191699">

Maybe it's me, but it's hard to distinguish when there are bunch of changes and to me hidden lines section looks like modified changes. What about a different color maybe primary (purple) one or some gray? I always used themes where green was used for modified changes and even if it's a different green (brighter) I still somehow manage to think that something was changed.

**Comment by eamodio** [comment]
Should be resolved in 4.8
