### ISSUE TITLE
Light: add border to sticky scroll section

### ISSUE THREAD

**Issue by svipas** [eamodio/vscode-amethyst-theme#16]
Right now you can't see a difference if it's a sticky scroll section.

<img width="652" alt="image" src="https://github.com/eamodio/vscode-amethyst-theme/assets/10441177/b228c40a-6ed1-4b45-9f9c-648f2e4df172">

<img width="669" alt="image" src="https://github.com/eamodio/vscode-amethyst-theme/assets/10441177/f49e8fdb-10c0-4590-9b62-40349c004fd1">

My suggestion would be maybe to add a border?

**Comment by svipas** [comment]
Maybe use the same background color and border of highlight line?

**Comment by eamodio** [comment]
I've added a bit of a stronger border in 4.8 -- does that help?
