### ISSUE TITLE
high contrast theme points to a non-existing file

### ISSUE THREAD

**Issue by rfejgin** [eamodio/vscode-amethyst-theme#5]
See this line:
https://github.com/eamodio/vscode-amethyst-theme/blob/master/themes/amethyst-dark-hc-color-theme.json#L5

It points to a file that does not exist, leading to an error when attempting to use this theme.

- Amethyst Theme Version:
3.0.0

**Comment by rfejgin** [comment]
Was it intended to say "amethyst-dark-color-theme.json" instead of the current ""./dark-amethyst-color-theme.json" ?

**Comment by eamodio** [comment]
This has now been fixed in 4.0 -- sorry about that!

**Comment by rfejgin** [comment]
Thanks for fixing!
